nelmio_api_doc:
  documentation:
    info:
      title: BileMo Application
      description: This is an application for phone company!
      version: 1.0.0
    paths:
      /api/login_check:
        post:
          tags:
            - Token
          operationId: postCredentialsItem
          summary: Allow to get JWT token for user to connect
          requestBody:
            description: Create one JWT token
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Credentials'

          responses:
            '200':
              description: 'token'
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Credentials'
    components:
      schemas:
        Token:
          type: object
          properties:
            token:
              type: string
              readOnly: true
        Credentials:
          type: object
          properties:
            username:
              type: string
              default: contact@smartmobile.com
            password:
              type: string
              default: password

      securitySchemes:
        Bearer:
          type: apiKey
          in: header
          name: Authorization # or another header name
    security:
      - Bearer: []
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
